name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt update;
        sudo apt install -y libnet1-dev libpcap-dev;

    - run: |
        clang -Ofast -o net_speeder net_speeder.c -lpcap -lnet -static;
        strip -s ./net_speeder;

    - uses: actions/upload-artifact@master
      with:
        name: net_speeder
        path: net_speeder
    - uses: actions/upload-artifact@master
      with:
        name: net_speeder
        path: net_speeder.sh
    - uses: actions/upload-artifact@master
      with:
        name: net_speeder
        path: nsrun.sh
